// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtv3N2l-QVr4F_ftXLx5-WbwiBk89xEAY',
    appId: '1:848230334891:web:ad806ccce94e6f5f0f52ee',
    messagingSenderId: '848230334891',
    projectId: 'sdapkapp',
    authDomain: 'sdapkapp.firebaseapp.com',
    storageBucket: 'sdapkapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAub0xI70KLsed58NwIv6sbOv-A7dUGqHk',
    appId: '1:848230334891:android:778dfc5edbaa56070f52ee',
    messagingSenderId: '848230334891',
    projectId: 'sdapkapp',
    storageBucket: 'sdapkapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChYQOFiYYI3itqdgypl4LJTXEJ3W-UDhc',
    appId: '1:848230334891:ios:49723a4ccac25a7f0f52ee',
    messagingSenderId: '848230334891',
    projectId: 'sdapkapp',
    storageBucket: 'sdapkapp.appspot.com',
    iosClientId: '848230334891-t2j4cv566l72068ehblfbfnb1t43uehl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdapkApp',
  );
}
