name: Build with Gradle and SonarQube

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize Gradle wrapper
        run: ./gradlew wrapper

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew com.example.sdapk_app sonar --info  # Replace 'myBuildTask' with your actual build task name
