name: SonarCloud Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: cachengo/actions-install-flutter@v1
        with:
          version: 'stable'  # Choose the desired Flutter version

      - name: Build Flutter app for scanning
        run: |
          flutter build apk --release --target-platform android --build-number ${{ github.run_number }}

      - name: Run OWASP ZAP scan on APK
        # ... (rest of your OWASP ZAP scan steps)
