name: SonarCloud Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # ... (other steps)

      - name: Build Flutter app for scanning
        run: |
          flutter build apk --release --target-platform android --build-number ${{ github.run_number }}

      - name: Run OWASP ZAP scan on APK
        run: |
          zapjs --target file://${{ github.workspace }}/build/app/outputs/apk/release/app-release.apk \
               --context-path / \
               --scan-policy standard --report-format html --report-file zap-report.html
